Switch to hvr's Travis config and test on 7.10

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,51 +1,81 @@
-language: haskell
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+language: c
+sudo: false
 
-ghc:
-  - 7.4
-  - 7.6
-  - 7.8
+cache:
+  directories:
+    - $HOME/.cabsnap
+    - $HOME/.cabal/packages
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+
+matrix:
+  include:
+    - env: CABALVER=1.16 GHCVER=7.4.2
+      compiler: ": #GHC 7.4.2"
+      addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.2],  sources: [hvr-ghc]}}
+    - env: CABALVER=1.16 GHCVER=7.6.3
+      compiler: ": #GHC 7.6.3"
+      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3],  sources: [hvr-ghc]}}
+    - env: CABALVER=1.18 GHCVER=7.8.4
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4],  sources: [hvr-ghc]}}
+    - env: CABALVER=1.22 GHCVER=7.10.3
+      compiler: ": #GHC 7.10.3"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
+
+before_install:
+ - unset CC
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 
 install:
- - mkdir sandbox
- - cabal sandbox init --sandbox sandbox
- - cabal sandbox add-source microlens
- - cabal sandbox add-source microlens-mtl
- - cabal sandbox add-source microlens-ghc
- - cabal sandbox add-source microlens-th
- - cabal sandbox add-source microlens-platform
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+   fi
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v microlens* > installplan.txt
+ - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
 
+# check whether current requested install-plan matches cached package-db snapshot
+ - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
+   then
+     echo "cabal build-cache HIT";
+     rm -rfv .ghc;
+     cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
+     cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
+   else
+     echo "cabal build-cache MISS";
+     rm -rf $HOME/.cabsnap;
+     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+     cabal install --only-dependencies --enable-tests --enable-benchmarks microlens*;
+   fi
+
+# snapshot package-db on cache miss
+ - if [ ! -d $HOME/.cabsnap ];
+   then
+      echo "snapshotting package-db to build-cache";
+      mkdir $HOME/.cabsnap;
+      cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
+      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
+   fi
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
- - cd microlens
- - cabal sandbox init --sandbox ../sandbox
- - cabal install --only-dependencies
- - cabal install --ghc-options=-Werror
- - cabal configure && cabal sdist
- - cd ..
-
- - cd microlens-mtl
- - cabal sandbox init --sandbox ../sandbox
- - cabal install --only-dependencies
- - cabal install --ghc-options=-Werror
- - cabal configure && cabal sdist
- - cd ..
-
- - cd microlens-ghc
- - cabal sandbox init --sandbox ../sandbox
- - cabal install --only-dependencies
- - cabal install --ghc-options=-Werror
- - cabal configure && cabal sdist
- - cd ..
-
- - cd microlens-th
- - cabal sandbox init --sandbox ../sandbox
- - cabal install --only-dependencies
- - cabal install --ghc-options=-Werror
- - cabal configure && cabal sdist
- - cd ..
-
- - cd microlens-platform
- - cabal sandbox init --sandbox ../sandbox
- - cabal install --only-dependencies
- - cabal install --ghc-options=-Werror
- - cabal configure && cabal sdist
- - cd ..
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal install --only-dependencies microlens*
+ - cabal install microlens*
+ - for lib in microlens*;
+   do
+     cd $lib;
+     cabal check;
+     cabal sdist;
+     cd ..;
+   done
